"""Stamp build metadata into ``mfl_desktop/_build_info.py`` (ADR-099/104).

Run by the build scripts/CI just before PyInstaller. Writes the current git
short SHA + build date so the packaged app's About box and diagnostics show
a real revision instead of "source". The file is gitignored — a plain source
checkout has none and ``version.build_revision()`` falls back to "source".
"""
from __future__ import annotations

import datetime
import subprocess
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "mfl_desktop" / "_build_info.py"


def _git(*args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", *args], cwd=_REPO, text=True, stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return ""


def main() -> int:
    rev = _git("rev-parse", "--short", "HEAD") or "unknown"
    dirty = _git("status", "--porcelain")
    if dirty:
        rev += "+dirty"
    date = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%d")
    _OUT.write_text(
        "# Generated by packaging/stamp_build_info.py — do NOT edit or commit.\n"
        f'REVISION = "{rev}"\n'
        f'BUILD_DATE = "{date}"\n',
        encoding="utf-8",
    )
    print(f"Stamped {_OUT.name}: REVISION={rev} BUILD_DATE={date}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
